### ISSUE TITLE
Specify for v2 ?

### ISSUE THREAD

**Issue by drbyte** [vyuldashev/nova-spatie-permission#2]
Hi @vyuldashev 
Thanks for this!

Would you be willing to update this to make it clear that this is built for `v2` of the Spatie package? 

The v3 release is likely to change some fields/features, and thus this NovaPackage would be broken. I think it would be helpful if it was clear that this was designed for v2.

**Comment by vyuldashev** [comment]
Hello,

I will make a new major version to support v3 of Spatie's package.

Also, I will and a compatibility table to readme.

Thanks.
